global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['127.0.0.1:9090']

  - job_name: 'node-export'
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'spring-prometheus-demo'
    scrape_interval: 5s
    scheme: http
    basic_auth:
      username: user
      password: pwd
    metrics_path: '/manage/prometheus'
    static_configs:
    - targets: ['host.docker.internal:8081']
